version: '3.2'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: web-apache
    volumes:
      - ./:/var/www/html:cached
    ports:
      - "8000:80"
  php:
    build:
      context: ./
      dockerfile: Dockerfile
      target: php-debug
    volumes:
      - ./:/var/www/html:cached
      - ./php.ini:/usr/local/etc/php/php.ini
  queue:
    build:
      context: ./
      dockerfile: Dockerfile
      target: php-prod
    depends_on:
      redis:
        condition: "service_healthy"
    volumes:
      - ./:/var/www/html:cached
    entrypoint: php /var/www/html/artisan queue:work
  scheduler:
    build:
      context: ./
      dockerfile: Dockerfile
      target: php-prod
    volumes:
      - ./:/var/www/html:cached
    entrypoint: php /var/www/html/artisan schedule:work
  db:
    image: mariadb:10.5
    environment:
       MYSQL_ROOT_PASSWORD: laravel
       MYSQL_DATABASE: laravel
       MYSQL_USER: laravel
       MYSQL_PASSWORD: laravel
    ports:
      - "3336:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
  redis:
    image: redis:6
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30

